config/routes.rb
Sealand::Application.routes.draw do

  root :to => 'plans#index'

  resources :attachments

  resources :materials

  resources :workshops

  resources :plans do
    resources :attachments
  end

  post 'api/material'     => 'api/materials#create', :as => 'api_create_material'
  get  'api/material'     => 'api/materials#index',  :as => 'api_materials'
  get  'api/material/:id' => 'api/materials#show',   :as => 'api_material'

  resources :users
  get "users/new"
  get "signup" => "users#new", :as => "signup"

  resources :sessions
  get "sessions/new"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

end

app/models/workshop.rb
class Workshop < ActiveRecord::Base
  attr_accessible :description, :lat, :lng, :name, :plan_id, :user_id
  belongs_to :user # the user that created the workshop
  belongs_to :plan # the plan this workshop uses
end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController

  before_filter :sanitize_html, :only => [ :create, :update ]

  # GET /workshops
  # GET /workshops.json
  def index
    @workshops = Workshop.all
    @locations = @workshops.map{|bar| [bar.lat, bar.lng]}.to_json

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @workshops }
    end
  end

  # GET /workshops/1
  # GET /workshops/1.json
  def show
    @workshop = Workshop.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @workshop }
    end
  end

  # GET /workshops/new
  # GET /workshops/new.json
  def new
    @workshop = Workshop.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @workshop }
    end
  end

  # GET /workshops/1/edit
  def edit
    @workshop = Workshop.find(params[:id])
  end

  # POST /workshops
  # POST /workshops.json
  def create
    @workshop = Workshop.new(params[:workshop])

    respond_to do |format|
      if @workshop.save
        format.html { redirect_to @workshop, notice: 'Workshop was successfully created.' }
        format.json { render json: @workshop, status: :created, location: @workshop }
      else
        format.html { render action: "new" }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /workshops/1
  # PUT /workshops/1.json
  def update
    @workshop = Workshop.find(params[:id])

    respond_to do |format|
      if @workshop.update_attributes(params[:workshop])
        format.html { redirect_to @workshop, notice: 'Workshop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workshops/1
  # DELETE /workshops/1.json
  def destroy
    @workshop = Workshop.find(params[:id])
    @workshop.destroy

    respond_to do |format|
      format.html { redirect_to workshops_url }
      format.json { head :no_content }
    end
  end

  private
  
  def sanitize_html
    params[:workshop][:description] = sanitize_clean( params[:workshop][:description] )
  end

end

app/views/workshops/_form.html.haml
- content_for(:sidebar) do
  = simple_form_for(@workshop) do |f|
    = f.error_notification

    .form-inputs
      = f.input :name
      = f.label :description
      .wysihtml5-toolbar{ "id" => "wysihtml5-toolbar", "style" => "display:none;" }
        %button{ "data-wysihtml5-command" => "bold" } 
          %b B
        %button{ "data-wysihtml5-command" => "italic" } 
          %i I
        %button{ "data-wysihtml5-command" => "insertOrderedList" } 1.
        %button{ "data-wysihtml5-command" => "insertUnorderedList" } &bull;
      = f.text_area :description
      = f.input :plan_id, :as => :select, :collection => Plan.all
      = f.input :lat
      = f.input :lng
    .form-actions
      = f.button :submit
    
#map{"style"=>"height: 600px; width: 100%;"}

:javascript
    OpenLayers.Control.Click = OpenLayers.Class(OpenLayers.Control, {                
      defaultHandlerOptions: {
          'single': true,
          'double': true,
          'pixelTolerance': 0,
          'stopSingle': false,
          'stopDouble': false
      },

      initialize: function(options) {
          this.handlerOptions = OpenLayers.Util.extend(
              {}, this.defaultHandlerOptions
          );
          OpenLayers.Control.prototype.initialize.apply(
              this, arguments
          ); 
          this.handler = new OpenLayers.Handler.Click(
              this, {
                  'click': this.trigger
              }, this.handlerOptions
          );
      }, 

      trigger: function(e) {
          var lonlat = map.getLonLatFromPixel(e.xy).transform(
              map.getProjectionObject(),  // to Spherical Mercator Projection
              new OpenLayers.Projection("EPSG:4326") // transform from WGS 1984
            );
          $('#workshop_lat').val(lonlat.lat);
          $('#workshop_lng').val(lonlat.lon);
      }

    });
    var map;
    function init(){
        map = new OpenLayers.Map('map');

        initMap(map, null, null);
        
        var click = new OpenLayers.Control.Click();
        map.addControl(click);
        map.zoomIn(8);
        click.activate();

    }

    var editor = new wysihtml5.Editor("workshop_description", { // id of textarea element
                                      toolbar:      "wysihtml5-toolbar", // id of toolbar element
                                      parserRules:  wysihtml5ParserRules // defined in parser rules set 
    }); 

app/views/workshops/edit.html.haml
%h1 Editing workshop

= render 'form'

= link_to 'Show', @workshop
\|
= link_to 'Back', workshops_path

app/views/workshops/index.html.haml
%h1 Listing workshops

- content_for(:sidebar) do
  - @workshops.each do |workshop|
    .teaser
      -#.teaserimage.pull-left= image_tag workshop.workshop_image.public_url, :style => "max-width: 100px; min-width: 100px; min-height:100px;"
      .teasertext
        .name 
          = link_to workshop.name, workshop_path(workshop)
        .description 
          != workshop.description

      -#%td= link_to 'Show', workshop
      -#%td= link_to 'Edit', edit_workshop_path(workshop)
      -#%td= link_to 'Destroy', workshop, :confirm => 'Are you sure?', :method => :delete

#map{"style"=>"height:600px; width: 100%"}
= link_to 'New Workshop', new_workshop_path

:javascript
  var locations = #{@locations};
  var map, layer;
  function init(){
    OpenLayers.ProxyHost="/proxy/?url=";
    map = new OpenLayers.Map('map');
    layer = new OpenLayers.Layer.WMS( "OpenLayers WMS", 
          "http://vmap0.tiles.osgeo.org/wms/vmap0", {layers: 'basic'} );
          
    map.addLayer(layer);
    map.setCenter(new OpenLayers.LonLat(0, 0), 0);

    var markers = new OpenLayers.Layer.Markers( "Markers" );
    map.addLayer(markers);

    var size = new OpenLayers.Size(21,25);
    var offset = new OpenLayers.Pixel(-(size.w/2), -size.h);
    locations.forEach( function(x,i) {
      var icon = new OpenLayers.Icon('http://www.openlayers.org/dev/img/marker.png',size,offset);
      markers.addMarker(new OpenLayers.Marker(new OpenLayers.LonLat(x[1], x[0]) ,icon));
    });

    map.addControl(new OpenLayers.Control.LayerSwitcher());

    map.zoomToMaxExtent();
    map.zoomIn( map.getZoom() + 1 );
  }

app/views/workshops/new.html.haml
%h1 New workshop

= render 'form'

= link_to 'Back', workshops_path

app/views/workshops/show.html.haml
%p#notice= notice
- content_for(:sidebar) do
  %p
    %b Name:
    = @workshop.name
  %p
    %b Description:
    != @workshop.description
  %p
    %b User:
    = @workshop.user_id
  %p
    %b Lat:
    = @workshop.lat
  %p
    %b Lng:
    = @workshop.lng
  %p
    %b Plan:
    = link_to @workshop.plan.name, plan_path(@workshop.plan)
  = link_to 'Edit', edit_workshop_path(@workshop)
  \|
  = link_to 'Back', workshops_path
  \|
  = link_to 'Destroy', @workshop, :confirm => 'Are you sure?', :method => :delete

#map{"style"=>"height:600px; width: 100%;"}

- workshop = @workshop.to_json

:javascript
  var workshop = #{workshop};
  var map, layer;
  function init(){
    map = new OpenLayers.Map('map');
    
    initMap(map,[workshop],null);
    
    map.setCenter(new OpenLayers.LonLat(workshop.lng, workshop.lat).transform(
              new OpenLayers.Projection("EPSG:4326"), // transform from WGS 1984
              map.getProjectionObject() // to Spherical Mercator Projection
            ), map.getZoom() + 3);
  }