config/routes.rb
Sealand::Application.routes.draw do

  root :to => 'plans#index'

  resources :attachments

  resources :materials

  resources :workshops

  resources :plans do
    resources :attachments
  end

  post 'api/material'     => 'api/materials#create', :as => 'api_create_material'
  get  'api/material'     => 'api/materials#index',  :as => 'api_materials'
  get  'api/material/:id' => 'api/materials#show',   :as => 'api_material'

  resources :users
  get "users/new"
  get "signup" => "users#new", :as => "signup"

  resources :sessions
  get "sessions/new"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

end

app/models/plan.rb
class Plan < ActiveRecord::Base
  attr_accessible :description, :name, :user_id, :plan_image, :attachments
  validates :name, :presence => true
  belongs_to :user
  has_file :plan_image, PlanImageUploader
  has_many :workshops
  has_many :attachments
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController

  before_filter :sanitize_html, :only => [ :create, :update ]

  before_filter :load_plans, :only => [:index, :new, :show, :edit]

  # GET /plans
  # GET /plans.json
  def index
    @workshops = Workshop.all
    @materials = Material.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @plans }
    end
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
    @plan = Plan.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @plan }
    end
  end

  # GET /plans/new
  # GET /plans/new.json
  def new
    @plan = Plan.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @plan }
    end
  end

  # GET /plans/1/edit
  def edit
    @plan = Plan.find(params[:id])
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(params[:plan])

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render json: @plan, status: :created, location: @plan }
      else
        format.html { render action: "new" }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /plans/1
  # PUT /plans/1.json
  def update
    @plan = Plan.find(params[:id])

    respond_to do |format|
      if @plan.update_attributes(params[:plan])
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy

    respond_to do |format|
      format.html { redirect_to plans_url }
      format.json { head :no_content }
    end
  end

  private

  def sanitize_html
    params[:plan][:description] = sanitize_clean( params[:plan][:description] )
  end

  def load_plans
    @plans = Plan.all
  end

end

app/views/plans/_form.html.haml
= simple_form_for(@plan) do |f|
  = f.error_notification
  .form-inputs
    = f.label :name
    = f.text_field :name, :class => "span5"
    = f.label :description
    .wysihtml5-toolbar{ "id" => "wysihtml5-toolbar", "style" => "display:none;" }
      %button{ "data-wysihtml5-command" => "bold" }
        %b B
      %button{ "data-wysihtml5-command" => "italic" } <i>I</i>
      %button{ "data-wysihtml5-command" => "insertOrderedList" } 1.
      %button{ "data-wysihtml5-command" => "insertUnorderedList" } &bull;
    = f.text_area :description, :class => "span5"
    .field
      = f.label :plan_image
      = image_tag @plan.plan_image.public_url, :style => "max-width: 284px; margin: 10px 0px;"
      = f.file_field :plan_image

    .alert.alert-info
      %h4.alert-heading Notice:
      You can add documents to your plan later.

  .form-actions
    = f.button :submit

:javascript
    var editor = new wysihtml5.Editor("plan_description", { // id of textarea element
                                      toolbar:      "wysihtml5-toolbar", // id of toolbar element
                                      parserRules:  wysihtml5ParserRules // defined in parser rules set
    });

app/views/plans/edit.html.haml
- content_for(:sidebar) do
  = link_to 'Back', :back, :class => 'btn'
  = render "shared/list_plans"

%h1 Editing plan

= render 'form'
= link_to 'Show', @plan

app/views/plans/index.html.haml
%p#notice= notice
- content_for(:sidebar) do
  .form-actions
    = link_to 'New Workshop', new_workshop_path, :class => 'btn btn-primary'
    = link_to 'New Plan', new_plan_path, :class => 'btn'
  = render "shared/list_plans"
  %a{"href" => "http://asapisland.wordpress.com/2012/04/12/sealand-multiversity-of-the-seven-seas/", "target" => "_blank"}
    %img.logo{"src" => "/assets/SMI_Logo_Top.png"}

#map{"style"=>"height:600px; width: 100%;"}

- matlocations = @materials.map{|mat| {'id'=>mat.id, 'name'=>mat.name, 'locations'=>mat.locations.map(&:attributes)} }.to_json
- workshops = @workshops.map { |ws| { 'workshop_url' => workshop_path(ws.id), 'plan_image' => ws.plan ? ws.plan.plan_image.public_url : nil }.merge(ws.attributes)  }.to_json

:javascript
  var materials = #{matlocations};
  var workshops = #{workshops};
  var map;
  function init(){
    map = new OpenLayers.Map('map');

    initMap(map,workshops,materials);
  }

app/views/plans/new.html.haml
- content_for(:sidebar) do
  = link_to 'Back', :back, :class => 'btn'
  = render "shared/list_plans"

%h1 New plan

= render 'form'

app/views/plans/show.html.haml
%p#notice= notice
- content_for(:breadcrumb) do
  %ul.breadcrumb
    %li
      %a{ "href" => plans_path()} Incubator 
      %span.divider /
    %li.active
      = @plan.name
.row 
  .span12
    %h2= @plan.name
    %br
.row
  .sidebar.span4
    .well
      %br
      = image_tag @plan.plan_image.public_url, :style => "max-width: 284px; "
      %br
      %br
      %h4 Description
      %p
        != @plan.description

      .pull-right= link_to '[edit]', edit_plan_path(@plan)

  .centerbar.span4
    %h3 Implementations of this Plan
    %br
    #map{"style"=>"height:200px;"}

      - workshops = @plan.workshops.to_json

      :javascript
        var workshops = #{workshops};
        var map;
        function init(){
          map = new OpenLayers.Map('map');

          initMap(map,workshops,null);
        }

    .workshops
      %ul
        - @plan.workshops.each do |workshop|
          %li=link_to workshop.name, workshop_path(workshop)
      = link_to 'Add new Workshop', new_workshop_path, :class => 'btn btn-primary'   
   
  .rightbar.span4
    %h3 Attachments
    %hr
    
    %ul
      = render @plan.attachments
    
    .addAttachment
      = render "attachments/form"