config/routes.rb
Sealand::Application.routes.draw do

  root :to => 'plans#index'

  resources :attachments

  resources :materials

  resources :workshops

  resources :plans do
    resources :attachments
  end

  post 'api/material'     => 'api/materials#create', :as => 'api_create_material'
  get  'api/material'     => 'api/materials#index',  :as => 'api_materials'
  get  'api/material/:id' => 'api/materials#show',   :as => 'api_material'

  resources :users
  get "users/new"
  get "signup" => "users#new", :as => "signup"

  resources :sessions
  get "sessions/new"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
    %title
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %script{"src" => "http://www.openlayers.org/api/2.11/OpenLayers.js"}
  %body{"onload" => "init();"}
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => "/"} 
            /%img{"src" => "/assets/SLM_Logo_36x36.png"}
            iLand Incubator
          -#
            .btn-group.pull-right
              - if current_user
                %a.btn.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  %i.icon-user
                  = current_user.email
                  %span.caret
                %ul.dropdown-menu
                  %li
                    %a{:href => "#"} Profile
                  %li.divider
                  %li
                    =link_to "Sign Out", logout_path
              - else
                %a.btn.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  Login
                  %span.caret
                %ul.dropdown-menu
                  %li
                    =link_to "login", login_path
                  %li.divider
                  %li
                    =link_to "Sign Up", signup_path
    .container
      - unless content_for?(:breadcrumb)
      - else
        .row
          .span12
            = yield(:breadcrumb)
      - unless content_for?(:sidebar)
        .row
          .span12
            = yield
      - else
        .row
          .span3
            .sidebar-nav
              = yield(:sidebar)
          .span9
            = yield
    %footer
      %p
        \© Copyright 2012
        %a{:href => "http://www.rhok.org/", :target => "_blank"} Random Hacks of Kindness
    = yield :filer_scripts